### ISSUE TITLE
example got many error

### ISSUE THREAD

**Issue by MollyCognito** [chrislapidas/react-expandable-rows#1]
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at ExpandableTable (ExpandableTable.tsx:32:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
```

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at ExpandableTable (ExpandableTable.tsx:32:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
resolveDispatcher @ react.development.js:1476
useState @ react.development.js:1507
ExpandableTable @ ExpandableTable.tsx:32
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20913
beginWork @ react-dom.development.js:22416
callCallback @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
recoverFromConcurrentError @ react-dom.development.js:25806
performConcurrentWorkOnRoot @ react-dom.development.js:25706
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18572 The above error occurred in the <ExpandableTable> component:

    at ExpandableTable (http://localhost:3000/static/js/bundle.js:160077:20)
    at TestTable
    at div
    at BillingDetails (http://localhost:3000/static/js/bundle.js:2208:72)
    at Routes (http://localhost:3000/static/js/bundle.js:166900:5)
    at div
    at Router (http://localhost:3000/static/js/bundle.js:166833:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:165642:5)
    at App (http://localhost:3000/static/js/bundle.js:81:80)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at ExpandableTable (ExpandableTable.tsx:32:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
```

...

**Comment by MollyCognito** [comment]
> ```
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (react.development.js:1476:1)
>     at useState (react.development.js:1507:1)
>     at ExpandableTable (ExpandableTable.tsx:32:1)
>     at renderWithHooks (react-dom.development.js:16175:1)
>     at mountIndeterminateComponent (react-dom.development.js:20913:1)
>     at beginWork (react-dom.development.js:22416:1)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
>     at invokeGuardedCallback (react-dom.development.js:4274:1)
>     at beginWork$1 (react-dom.development.js:27405:1)
> ```
> 
> ```
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (react.development.js:1476:1)
>     at useState (react.development.js:1507:1)
>     at ExpandableTable (ExpandableTable.tsx:32:1)
>     at renderWithHooks (react-dom.development.js:16175:1)
>     at mountIndeterminateComponent (react-dom.development.js:20913:1)
>     at beginWork (react-dom.development.js:22416:1)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
>     at invokeGuardedCallback (react-dom.development.js:4274:1)
>     at beginWork$1 (react-dom.development.js:27405:1)
> resolveDispatcher @ react.development.js:1476
> useState @ react.development.js:1507
> ExpandableTable @ ExpandableTable.tsx:32
> renderWithHooks @ react-dom.development.js:16175
> mountIndeterminateComponent @ react-dom.development.js:20913
> beginWork @ react-dom.development.js:22416
> callCallback @ react-dom.development.js:4161
> invokeGuardedCallbackDev @ react-dom.development.js:4210
> invokeGuardedCallback @ react-dom.development.js:4274
> beginWork$1 @ react-dom.development.js:27405
> performUnitOfWork @ react-dom.development.js:26513
> workLoopSync @ react-dom.development.js:26422
> renderRootSync @ react-dom.development.js:26390
> recoverFromConcurrentError @ react-dom.development.js:25806
> performConcurrentWorkOnRoot @ react-dom.development.js:25706
> workLoop @ scheduler.development.js:266
> flushWork @ scheduler.development.js:239
> performWorkUntilDeadline @ scheduler.development.js:533
> react-dom.development.js:18572 The above error occurred in the <ExpandableTable> component:
> 
>     at ExpandableTable (http://localhost:3000/static/js/bundle.js:160077:20)
>     at TestTable
>     at div
>     at BillingDetails (http://localhost:3000/static/js/bundle.js:2208:72)
>     at Routes (http://localhost:3000/static/js/bundle.js:166900:5)
>     at div
>     at Router (http://localhost:3000/static/js/bundle.js:166833:15)
>     at BrowserRouter (http://localhost:3000/static/js/bundle.js:165642:5)
>     at App (http://localhost:3000/static/js/bundle.js:81:80)
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
> logCapturedError @ react-dom.development.js:18572
> update.callback @ react-dom.development.js:18605
> callCallback @ react-dom.development.js:13122
> commitUpdateQueue @ react-dom.development.js:13143
> commitLayoutEffectOnFiber @ react-dom.development.js:23290
> commitLayoutMountEffects_complete @ react-dom.development.js:24578
> commitLayoutEffects_begin @ react-dom.development.js:24564
> commitLayoutEffects @ react-dom.development.js:24502
> commitRootImpl @ react-dom.development.js:26779
> commitRoot @ react-dom.development.js:26638
> finishConcurrentRender @ react-dom.development.js:25848
> performConcurrentWorkOnRoot @ react-dom.development.js:25765
> workLoop @ scheduler.development.js:266
> flushWork @ scheduler.development.js:239
> performWorkUntilDeadline @ scheduler.development.js:533
> react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (react.development.js:1476:1)
>     at useState (react.development.js:1507:1)
>     at ExpandableTable (ExpandableTable.tsx:32:1)
>     at renderWithHooks (react-dom.development.js:16175:1)
>     at mountIndeterminateComponent (react-dom.development.js:20913:1)
>     at beginWork (react-dom.development.js:22416:1)
>     at beginWork$1 (react-dom.development.js:27381:1)
>     at performUnitOfWork (react-dom.development.js:26513:1)
>     at workLoopSync (react-dom.development.js:26422:1)
>     at renderRootSync (react-dom.development.js:26390:1)
> ```
> 
> ...
